### ISSUE TITLE
打包后运行失败

### ISSUE THREAD

**Issue by Angelyeye** [bearmr/tapdPhshDingDingRobot#2]
![image](https://user-images.githubusercontent.com/58071062/178667141-a838e49d-6c3b-47a7-b9cd-76afa7dbcb17.png)

**Comment by bearmr** [comment]
这边打包运行是成功的 
cmd 在对应的目录 java -jar tapdPhshDingDingRobot-0.0.1-SNAPSHOT.jar

**Comment by bearmr** [comment]
![image](https://user-images.githubusercontent.com/10863395/178668262-6537ac65-2cc4-4b79-b049-458d1f52f2db.png)
